services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python /app/manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
      - .:/app/

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./.redis/data/:/root/redis
      - ./.redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_DB: greenlight
  #     POSTGRES_PASSWORD: psswd
  #     POSTGRES_USER: user
  #   volumes:
  #     - ./.postgres-data/db:/var/lib/postgresql/data 
  #   ports:
  #     - 5432:5432
