# Generated by Django 5.0.7 on 2024-07-28 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alert_coin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='coin',
            field=models.CharField(default='btcusdt', help_text="The cryptocurrency pair for this alert (e.g., 'btcusdt').", max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('triggered', 'Triggered'), ('deleted', 'Deleted')], default='created', help_text='The current status of the alert.', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='target_price',
            field=models.FloatField(help_text='The target price at which the alert is triggered.'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(help_text='The user associated with this alert.', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
